### ISSUE TITLE
feature request: alias $HOME as ~ for zoxide results

### ISSUE THREAD

**Issue by danielx** [joshmedeski/t-smart-tmux-session-manager#10]
Thanks for building this, i love how it simplifies my workflow!

Though on my work computer i am forced to use my email as the username which makes the home path quite long.

I don't have the need for the entire $HOME path so i'd prefer to have that aliased as '~'

**Comment by joshmedeski** [comment]
So the substitution didn't work with zsh and I did some testing but couldn't get it to work but I decided to revert the feature for now.

I did some refactoring of the t script today, so if you wanna pull from main and try again we'll need to make sure it can work on bash, zsh, and fish.
