### ISSUE TITLE
Feature Request: Better git url handling

### ISSUE THREAD

**Issue by tanishqmanuja** [joshmedeski/t-smart-tmux-session-manager#100]
It would be great if --repo flag supported these as input:
- joshmedeski/t-smart-tmux-session-manage
- https://github.com/joshmedeski/t-smart-tmux-session-manager
- https://github.com/joshmedeski/t-smart-tmux-session-manager.git (currently supported)

**Comment by joshmedeski** [comment]
I agree. I'm currently rewriting it in Go (see https://github.com/joshmedeski/sesh).

I'll move this ticket over when I get to a stable point on the project.
