### ISSUE TITLE
Starting t from inside a Tmux Session locks the pane

### ISSUE THREAD

**Issue by Msouza91** [joshmedeski/t-smart-tmux-session-manager#104]
I just installed the extension in an attempt at a better workflow outside vim in which I am currently using tmux-sessionizer, I have the binaries on path, but when it tries to start fzf-tmux it is locking up, I am assuming that it is when it gets to that part because it was not finiding that tool before because I had a minimal install of fzf, so I updated with the git install script using --all and when I tried to open the pop-up from inside a session the pane crashes with no input to shell. I can open a new pane and kill the previous one, but got me tripped up.

Sorry for the recording format, I got to figure out how to select the screen for the ffmpeg recording yet. But you should be able to see the issue.
https://github.com/joshmedeski/t-smart-tmux-session-manager/assets/19522556/0ce425b8-c104-4ba9-a2d4-1e0dd343bfad

[tmux-client-364682.log](https://github.com/joshmedeski/t-smart-tmux-session-manager/files/13905799/tmux-client-364682.log)
[tmux-server-364684.log](https://github.com/joshmedeski/t-smart-tmux-session-manager/files/13905800/tmux-server-364684.log)

**Comment by joshmedeski** [comment]
I've seen this before, it's usually a bad `FZF_TMUX_OPTS` value. Can you make sure you're using the latest version of fzf and if you set that variable what is the value?

**Comment by Msouza91** [comment]
I am on fzf 0.45.0 and just had a vanilla install, I only set FZF_DEFAULT_OPTS with a colorscheme. Will try to set the defaults from README and check if it changes anything.

**Comment by Msouza91** [comment]
It didn't solve the issue, but noticed now recording a new test showing the variable output that I set on my profile for testing, when I start t, the tmux pane name changes to bash although I'm using zsh I wonder why and would hazard a guess that there is some shenanigans happening there.

https://github.com/joshmedeski/t-smart-tmux-session-manager/assets/19522556/fa31b934-03b7-4268-a044-6d4b2d48d36d

**Comment by joshmedeski** [comment]
The most common issue I've seen is the [prerequisites](https://github.com/joshmedeski/t-smart-tmux-session-manager?tab=readme-ov-file#prerequisites) are mismatched. Please make sure you have the right versions of everything. 

Sometimes the dependencies built-in to your machine are old.

**Comment by Msouza91** [comment]
This is a good point, but I don't think it applies to my case tho, I updated fzf for testing, but I was on 0.41 when I first installed, bumped to 0.45 just to be on latest in case it would change anything.

Just to sanity check, is any of this Mac Specific? I don't think it should matter since these are all shell tools running on top of more or less the same base "zsh".
I'm on **Ubuntu 22.04** with **AwesomeWm** and **Kitty** as my terminal emulator.

Here are the versions of the dependencies and a directory listing of my plugins folder for reference.
![image](https://github.com/joshmedeski/t-smart-tmux-session-manager/assets/19522556/ff09afe1-34b5-43c0-b9be-f43b5538449c)

**Comment by joshmedeski** [comment]
This script uses bash, not zsh. So perhaps update bash to a newer version?

**Comment by joshmedeski** [comment]
Also, can you try connecting to a session directly with `t {name}`? I'd like to know if it's just fzf failing or something else.

**Comment by Msouza91** [comment]
Connecting to a session outside tmux works fine, just noticed that the fzf replacement for ^-R also is locking the pane, so probably fzf related, sorry for taking your time, will try to open an issue there and see what comes of it.
I'll close this one for now and will update with my solution (hopefuly) for someone that might face the same problem.

**Comment by Msouza91** [comment]
Seems like there is an issue with 3.2a on Ubuntu 22.04 repos and FZF, I compiled 3.4 from source and the popup worked as expected! People on 23.04 should be fine I guess 🤷🏼‍♂️

**Comment by joshmedeski** [comment]
I'm currently working on a rewrite in GoLang! [Check it out here](https://github.com/joshmedeski/sesh)

It's getting pretty close to be ready for use, it will be much easier to work with and you'll be able to customize fzf to your needs
