### ISSUE TITLE
Can I bind the command to unprefixed Control-Space?

### ISSUE THREAD

**Issue by jpericavcc** [joshmedeski/t-smart-tmux-session-manager#106]
Here is how I set the bindings for the plugin. It works

```
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
set -g @t-bind "none" # unbind default
set -g @t-bind "Space"
```

How can I bind the command to unprefixed Ctrl-Space?

Thanks for a great plugin!

**Comment by joshmedeski** [comment]
Hey, you're welcome!

There isn't currently a way to "unbind" it. You could change the binding to something else if it conflicts with your workflow.

I have a video on [macos keyboard shortcuts for tmux](https://www.youtube.com/watch?v=BLp61-Lq0kQ) that might prove useful, you can add keybindings to your terminal emulator to simulate the t command.

p.s. I'm currently working on a rewrite in GoLang! [Check it out here](https://github.com/joshmedeski/sesh)
