### ISSUE TITLE
How to bind the popup without prefix key

### ISSUE THREAD

**Issue by Tanish2002** [joshmedeski/t-smart-tmux-session-manager#107]
sorry if this a silly question. I'm new to tmux in general 😅

The provided variable config `set -g @t-bind "K"` can be only used to bind the popup to `bind-key` meaning I have to press `<prefix>@t-bind`.

I would like to bind it to something like `M-o`(M=Alt). How could I do that?

**Comment by joshmedeski** [comment]
Check out the bonus section of the readme. You can configure the terminal emulator of your choosing to anything you’d like https://github.com/joshmedeski/t-smart-tmux-session-manager#bonus-macos-keyboard-shortcut

**Comment by Tanish2002** [comment]
Thanks that solved my problem!

I do think though an option to set binding outside the prefix table should be available, and this shouldn't be left to the terminal. But this works for me 😄.

Closing.
