### ISSUE TITLE
hangs until I restart my terminal and re-attach tmux

### ISSUE THREAD

**Issue by bbigras** [joshmedeski/t-smart-tmux-session-manager#108]
When I invoke t-smart-tmux-session-manager, it opens, shows the sessions but hangs for a reason.

I can "fix" it by restarting my terminal and re-attaching tmux.

This might have happened after a t-smart-tmux-session-manager update. Not sure yet. I'll try to find out.

I tried with foot and alacritty. and I tried disabling all my other tmux plugins.

zsh

**Comment by bbigras** [comment]
It started with 2.7.0 when the dialog moved to the bottom.

**Comment by joshmedeski** [comment]
Hey, check out https://github.com/joshmedeski/t-smart-tmux-session-manager/issues/104

Basically, your fzf is probably out of date. Rather than trying to fix it I highly recommend you switch to sesh:
https://github.com/joshmedeski/sesh

**Comment by bbigras** [comment]
Weird, I'm already using fzf 0.45.0.

I'll check sesh.

I'll close this issue as a duplicate.

Thanks!
