### ISSUE TITLE
getting error since last update

### ISSUE THREAD

**Issue by H4ckint0sh** [joshmedeski/t-smart-tmux-session-manager#12]
````
/Users/ali/.tmux/plugins/t-smart-tmux-session-manager/bin/t: line 53: cd: ~/Desktop/projects/joshuto: No such file or directory
````
But i can see that this directory exist in the given path.

**Comment by joshmedeski** [comment]
Okay thanks, I'll look into it today.

**Comment by joshmedeski** [comment]
Which shell are you using? I can't recreate this error.

**Comment by H4ckint0sh** [comment]
I am using zsh, reverting the last two commits solves my problem.

**Comment by joshmedeski** [comment]
I'll do some tests on the `~` subsitution in zsh, thanks.

**Comment by joshmedeski** [comment]
Hey @H4ckint0sh, I dropped the $HOME substitution feature and make some improvements on the script, please test it out and let me know if there are any more problems, thanks!

**Comment by H4ckint0sh** [comment]
> Hey @H4ckint0sh, I dropped the $HOME substitution feature and make some improvements on the script, please test it out and let me know if there are any more problems, thanks!

The error is gone now and i have noticed the plugin to be much faster now. Thanks 🙏
