### ISSUE TITLE
feature request: exlude paths for already open sessions

### ISSUE THREAD

**Issue by danielx** [joshmedeski/t-smart-tmux-session-manager#18]
Hello, one thing i've been thinking about is the double entries of open sessions and their zoxide paths.

Did some research and by using this tmux query one can get the tmux sessions base paths:
```bash
$ tmux list-sessions -F '#{session_path}'
/Users/daniel/.dotfiles
/Users/daniel/projects/hex
/Users/daniel/.dotfiles/tmux/plugins/t-smart-tmux-session-manager
...
```

tmux manual says
```
session_path                    Working directory of session
```
So i assume that should be stable over a session.

I was thinking that some logic could be added (not sure how yet) to exclude the zoxide entries that already have sessions open.

**Comment by joshmedeski** [comment]
So far I really like the short concise session names at the top of the results, it makes it easy to match with fzf.

<img width="1374" alt="Screenshot 2023-02-28 at 4 33 19 PM" src="https://user-images.githubusercontent.com/2036594/221996975-11619706-381d-4876-bc23-5af09a94fce7.png">

I got it working, but it's not obvious that dotfiles already running. Is that alright with you? Do you like the tradeoff of not knowing which is a sessions and which is a zoxide results?

<img width="1374" alt="Screenshot 2023-02-28 at 4 48 11 PM" src="https://user-images.githubusercontent.com/2036594/221999363-591ee717-dc4d-4bef-a6ac-2242be1fac41.png">

**Comment by danielx** [comment]
Hmm, that's true.

And i guess having them merged in one list is equivalent to using the zoxide filter view when i think about it a bit more.

So probably not worth to add the complexity to keep it free from duplicates and still have the tmux sessions be at the top of the results with their short names.

Thanks for taking the time to look into this 😄
