### ISSUE TITLE
Consdier adding version requirement

### ISSUE THREAD

**Issue by EdvardSire** [joshmedeski/t-smart-tmux-session-manager#20]
Thank you for this lovely utility.

I had some trouble getting the session manager overlay to work, after looking at the implementation it turned out that i had an old version of fzf. The argument `--border-label` was added in [fzf@0.35.0](https://github.com/junegunn/fzf/releases/tag/0.35.0) and was the reason the session manager overlay wasn't working for me. The thing is that it closes immediately so it can be a bit tricky to figure out.

What do you think about adding a version requirement to the [README](https://github.com/joshmedeski/t-smart-tmux-session-manager#prerequisites)?

**Comment by joshmedeski** [comment]
Thanks for clarifying when the border label argument got added. I updated the README 😄
