### ISSUE TITLE
Unknown option: --border-label

### ISSUE THREAD

**Issue by abhijeetsrivastava** [joshmedeski/t-smart-tmux-session-manager#21]
Unknown option: --border-label

I am using tmux 3.3a, and getting above error when running t without args.

Environment:
Ubuntu on wsl

**Comment by joshmedeski** [comment]
What version of fzf are you using? The fzf border label requires >=0.35.0

**Comment by abhijeetsrivastava** [comment]
updated, and is now working. Thanks!
