### ISSUE TITLE
How to change the key mapping to trigger the fzf-tmux popup?

### ISSUE THREAD

**Issue by alphaone** [joshmedeski/t-smart-tmux-session-manager#23]
> By default, this plugin is bound to <prefix>+T which triggers a fzf-tmux popup that display zoxide results.

How can one change the default and use a different key combo to trigger the popup?

**Comment by joshmedeski** [comment]
Great question. In order to add your own custom key binding to trigger the `t` script, add the following to your `tmux.conf`:

```
bind-key J run-shell "t"
```

I've also added it to the README for future reference.

**Comment by alphaone** [comment]
Thanks, Josh.

Great little plugin you created here.

**Comment by peterkracik** [comment]
Hi, 
thank you for the plugin! 

For some reason this shortcut does not work for me, it throws me:

```bash
't' returned 127
```
in my .tmux.conf
```conf
bind-key S run-shell "t"
```

If I run `t` as a command it works as it is supposed to, but it does not with the TMUX binding. 
I also tried to replace `"t"` with the full path.

any idea?

**Comment by peterkracik** [comment]
> What shell environment did you configure the t script for (zsh, fish, bash)?
> 
> You may have to explicitly set your default shell in `.tmux.conf`
> 
> ```
> set-option -g default-shell /bin/zsh
> ```

it seems like there's a problem with the Path. I added them to the .zshrc (I can call `t` in the shell).
so if I do it this way, it works
```conf
bind-key S run-shell "~/.tmux/plugins/t-smart-tmux-session-manager/bin/t"
```
I will search for what I did wrong, but this is good enough for me, you can close the issue. 
And at least if somebody else has this problem, it will be here:)

**Comment by joshmedeski** [comment]
When in doubt using the full path is a great solution.

If you learn anything new feel free to let us know, glad it's working!
