### ISSUE TITLE
unknown action: change-prompt(directory> )

### ISSUE THREAD

**Issue by b13v** [joshmedeski/t-smart-tmux-session-manager#24]
Hi Josh

Getting error if I try to run script in interactive mode but just typing 't' -> unknown action: change-prompt(directory> ).
I'm using fish but this message I got using bash and zsh too.

**Comment by joshmedeski** [comment]
Make sure to also install all of the [prerequisites](https://github.com/joshmedeski/t-smart-tmux-session-manager#prerequisites).

That error sounds like you haven't installed fzf (or you might have an outdated version).

**Comment by b13v** [comment]
Hi Josh
thank you very much, yes my version of fzf was 0.20. I upgraded it and now it works!
