### ISSUE TITLE
`fzf-tmux -p` requires tmux >= 3.2

### ISSUE THREAD

**Issue by jswalton** [joshmedeski/t-smart-tmux-session-manager#37]
Hi Josh,

Thanks for the great work here on this plugin. I just wanted to let you know of a small issue I've found:

### Problem:
It seems as if tmux >= 3.2 is required to make things work as is with [t.sh](https://github.com/joshmedeski/t-smart-tmux-session-manager/blob/main/bin/t). As of right now I encounter problems with any `fzf-tmux` command that has a `-p` flag inside of tmux 3.0a. This in short causes nothing to happen when running `t.sh` from it's tmux binding while inside of tmux < 3.2 and things lock up. A simple solution might be specifying that tmux >= 3.2 is needed on the "Prerequisites' section of the README.md. I'm happy to contribute that if this is a reproducible problem.

### Workaround: 
if fzf-tmux can't use the popup, and one is using tmux <3 .2, then the `run-shell` command should be run with the `-b` flag on the following line:
https://github.com/joshmedeski/t-smart-tmux-session-manager/blob/main/t-smart-tmux-session-manager.tmux#L14
 
### Environment Details:
tmux 3.0a
fzf 0.35.1
Shell: zsh 5.8
OS: Ubuntu 20.04.6 LTS on Windows 10 x86_64

References: 
https://raw.githubusercontent.com/tmux/tmux/3.2/CHANGES
https://github.com/junegunn/fzf/blob/master/ADVANCED.md#popup-window-support

Best,
Another Josh

**Comment by joshmedeski** [comment]
Thanks for pointing this out Josh, I updated the README.

We're going through a big refactor (see #33) so I don't recommend contributing until that work is completed.

If it's important to you to support tmux `<3.2` you're welcome to add the contribution but considering that release is now a 2+ years old I'm alright with it just being a requirement on the README

**Comment by jswalton** [comment]
> Thanks for pointing this out Josh, I updated the README.
> 
> We're going through a big refactor (see #33) so I don't recommend contributing until that work is completed.
> 
> If it's important to you to support tmux `<3.2` you're welcome to add the contribution but considering that release is now a 2+ years old I'm alright with it just being a requirement on the README

Sounds good @joshmedeski! I agree with not supporting a release as old as those < 3.2. I just happen to be stuck on on 3.0a for now because of work constraints. Thanks!
