### ISSUE TITLE
Commands on tmux sessions

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/t-smart-tmux-session-manager#40]
Add the following commands when filtering by tmux sessions (`^s`)
- [ ] `^d` delete session (and reload existing sessions)
- [ ] Handle if you delete the session you're currently in (reopen tmux?)
- [ ] `^v` toggle preview? (similar to the `<prefix>s` command "Select a new session for the attached client interactively.")

**Comment by RiteshChepuri** [comment]
I think ^x will make more sense to kill session, and change zoxide to ^z, ^d is the best for searching the directories

**Comment by joshmedeski** [comment]
When I bring up fzf keybindings each person seems to have their own preferences. I'm going to consider this as a sign to create some sane defaults and add the ability to remap any/all commands to their liking. 😁

**Comment by RiteshChepuri** [comment]
Yeah Sounds good!

**Comment by joshmedeski** [comment]
Hey @RiteshChepuri, [check out sesh](https://github.com/joshmedeski/sesh), I've rewritten this project in GoLang and left the fzf integration to the developer so they can customize it to whatever they want!

**Comment by RiteshChepuri** [comment]
Yeah I made some modifications to the previous t-smart- session manager and it's been working great. And I'll use sesh in the future.
