### ISSUE TITLE
Creates but can't switch to session

### ISSUE THREAD

**Issue by b4rlw** [joshmedeski/t-smart-tmux-session-manager#46]
I just updated all my tmux plugins, and I'm now having trouble switching sessions.

When I select something from the zoxide menu, it creates the session, but has trouble switching to it and throws the following error:
```
'/Users/user/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t' returned 2
```
This could be a problem with my own config though. I've tried uninstalling all my plugins and reinstalling only this one, but the issue seems to persist.

Any ideas what could be causing this?
Many thanks.

**Comment by joshmedeski** [comment]
What version of bash are you using? This plugin now requires bash >= 4.0

[Learn more here](https://github.com/joshmedeski/t-smart-tmux-session-manager/releases/tag/v2.0.1)

**Comment by b4rlw** [comment]
My apologies, that was it! Apparently I never installed bash through Homebrew, and therefore I was using whatever outdated version ships with Ventura.
