### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by hqkhan** [joshmedeski/t-smart-tmux-session-manager#48]
Hello. Ever since I've updated the plugin, I'm finding that the keybind won't work anymore. `C-b T` does not bring up the tmux-popup. I can call `t` directly which works fine. Doing so via keybind does not work. Do you have any ideas as to what's happening?

**Comment by joshmedeski** [comment]
What version of bash are you using? This plugin now requires bash >= 4.0

[Learn more here](https://github.com/joshmedeski/t-smart-tmux-session-manager/releases/tag/v2.0.1)

**Comment by hqkhan** [comment]
I am using bash >= 4.0

```
search_load_gen/src/ElastiCacheSearch on  mainline
 bash --version
GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I can also see my keybind:
```
bind-key    -T prefix       T                    run-shell /home/hqkhan/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t
```

I'm also using:
```
  - { key: J, mods: Command, chars: "\x02\x54" } # open t - tmux smart session manager
```
in Alacritty.

**Comment by joshmedeski** [comment]
Hmm, does the `t` script work in your CLI? Maybe there's another dependency issue.

**Comment by hqkhan** [comment]
Yes, the t script works fine. I just can't invoke it using tmux

**Comment by joshmedeski** [comment]
I recommend setting this in your `tmux.conf`

```
set -g @t-bind 'T'
```

And try killing tmux completely and trying agin. You can also replace 'T' with a different letter to see if it can work.

**Comment by hqkhan** [comment]
I tried exactly that. Also tried different keybinds. Restarted tmux server but it still hasn't worked. I'll give it another shot

**Comment by joshmedeski** [comment]
Okay, let me know if you get to the root of it. Even restarting your computer might help.

**Comment by joshmedeski** [comment]
Did you rebind your prefix key? If so, you'll have to change the hex code in your Alacritty config.

**Comment by hqkhan** [comment]
> Did you rebind your prefix key? If so, you'll have to change the hex code in your Alacritty config.

No I did not. I just the default prefix. I've been using this plugin for a while without issues. I have a fork as well. I updated from upstream and now am having a hard time. I did try your version as opposed to my fork but both had this issue

**Comment by hqkhan** [comment]
Uhh. So, I killed my server, left my ssh connection. After that, everything is working fine :| lol

Thank you!

**Comment by joshmedeski** [comment]
That's good news! I guess the SSH layer must have created some sort of additional issue.
