### ISSUE TITLE
t command not found!

### ISSUE THREAD

**Issue by H4ckint0sh** [joshmedeski/t-smart-tmux-session-manager#5]
iI have done everything the documentation mentions, yet the t command is not found by zsh. The <prefix>T command works as intended though.

**Comment by joshmedeski** [comment]
Does `$HOME/.config/tmux/plugins/t-smart-tmux-session-manager` exist? Perhaps tpm has installed the plugin somewhere else on your machine.

**Comment by H4ckint0sh** [comment]
OH! Thanks for the quick replay and for this wonderful peace of script. Yes my .tmux map was not inside .config. The moment I corrected that url it begun to work.

Thank you again.

**Comment by joshmedeski** [comment]
Okay great, I've added some additional instructions in the readme to help people identify where their plugins directory is located. See https://github.com/joshmedeski/t-smart-tmux-session-manager/commit/25d9ce2f5850ff19ddbda6cc5d99d8e5ff2dcd46
