### ISSUE TITLE
Improve session name

### ISSUE THREAD

**Issue by TomDeneire** [joshmedeski/t-smart-tmux-session-manager#50]
Hi @joshmedeski,

I've been using the t script a lot lately and I'm really liking it! Thanks. 

One thing I've noticed though is that I'd like the tmux session name to be a bit more descriptive than just the basename of the selected directory. Often I'm in a directory that is called "application" or "python" or "code" or "bin" and that's not really helpful in the list of sessions. Sometimes I even have duplicate names because of this.

As an experiment I've replace line 170:

`SESSION_NAME=$(echo "$FOLDER" | tr ' .:' '_')`

with

`SESSION_NAME=$(echo $RESULT| tr ' .:' '_' | awk -F "/" '{print $(NF-1)"/"$NF}')`

which gives you just one more directory, hence I get things like "docstore/application", "csvtool/python", or "projects/code".

Do you feel this might be something you could include in the t-script as a a feature?

As a side note: ideally you'd like to customize stuff like this, but also other things like the window header and such. On the other hand, I like that t is just one plain bash script and that it's ready to go zero config!

**Comment by joshmedeski** [comment]
Great idea! I've added a shell flag to support the parent dir in the session name. Check out the PR for instructions how to test and I can merge it if it looks good to you.
