### ISSUE TITLE
Error when running t outside a tmux session

### ISSUE THREAD

**Issue by zeroknots** [joshmedeski/t-smart-tmux-session-manager#54]
Im getting this error:

```
/Users/user/.config/tmux/plugins/t-smart-tmux-session-manager/bin/T: line 116: conditional binary operator expected
/Users/user/.config/tmux/plugins/t-smart-tmux-session-manager/bin/T: line 116: syntax error near `$FZF_TMUX_OPTS'
/Users/user/.config/tmux/plugins/t-smart-tmux-session-manager/bin/T: line 116: `		if [[ ! -v $FZF_TMUX_OPTS ]]; then'
```

when I use the session manager from within an existing tmux session its workin fine.

**Comment by albertilagan** [comment]
> Im getting this error:
> 
> ```
> /Users/user/.config/tmux/plugins/t-smart-tmux-session-manager/bin/T: line 116: conditional binary operator expected
> /Users/user/.config/tmux/plugins/t-smart-tmux-session-manager/bin/T: line 116: syntax error near `$FZF_TMUX_OPTS'
> /Users/user/.config/tmux/plugins/t-smart-tmux-session-manager/bin/T: line 116: `		if [[ ! -v $FZF_TMUX_OPTS ]]; then'
> ```
> 
> when I use the session manager from within an existing tmux session its workin fine.

Maybe you're using bash version < 4? I had the same issue before, updating bash fixes it.

**Comment by joshmedeski** [comment]
You are most likely using an older version of bash like @albertilagan mentioned. Please let us know if updating bash fixes it.

**Comment by landon-buttars-wgu** [comment]
Seeing this while using ZSH on version 5.9 (stable as of 20/9).

**Comment by Buttars** [comment]
Seeing this while using ZSH on version 5.9 (stable as of 20/9).

**Comment by albertilagan** [comment]
> Seeing this while using ZSH on version 5.9 (stable as of 20/9).

what does it say when you run `bash --version`?

**Comment by Buttars** [comment]
`GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)` so it does seem to be a bash version issue. Let me try and update bash and see how it works.

**Comment by Buttars** [comment]
Okay, it seems like Mac ships a version of bash that is several versions out of date. I had to `brew install bash` for this to work which seemed unintuitive since mac ships with bash. Guess you can't trust apple to ship up-to-date binaries.

Solved for me.

**Comment by joshmedeski** [comment]
Glad that fixed it @Buttars. Check out [v2.0.1 release notes](https://github.com/joshmedeski/t-smart-tmux-session-manager/releases/tag/v2.0.1) for more info.

@zeroknots please let us know if upgrading bash fixes your issue.

**Comment by zeroknots** [comment]
really appreciate the help @joshmedeski @albertilagan 

indeed upgrading bash did the trick
