### ISSUE TITLE
Cannot use t to jump to another session

### ISSUE THREAD

**Issue by kevinrobayna** [joshmedeski/t-smart-tmux-session-manager#63]
I literally just updated all the tmux plugins in a while and i'm getting this error now 😅 

when i run `/Users/kevinrobayna/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t` it exits with error 2 and this is the output
```
 /Users/kevinrobayna/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t
/Users/kevinrobayna/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t: line 119: conditional binary operator expected
/Users/kevinrobayna/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t: line 119: syntax error near `$FZF_TMUX_OPTS'
/Users/kevinrobayna/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t: line 119: `                if [[ ! -v $FZF_TMUX_OPTS ]]; then'
```

my shell `Shell: zsh 5.9`

**Comment by kevinrobayna** [comment]
^ granted i haven't updated in a couple of months 🤣

**Comment by joshmedeski** [comment]
Please update bash on your system `brew install bash`

**Comment by kevinrobayna** [comment]
oh 😅 that solved the issues 😅 

i was trying with this 
```
		if [[ -z $FZF_TMUX_OPTS ]]; then
			FZF_TMUX_OPTS="-p 53%,58%"
		fi

```

but that created other issues i was clearly using my default mac version of bash because once installed it just worked

Thank you very much @joshmedeski!!!

**Comment by joshmedeski** [comment]
You're welcome. It's the most common issue I've had since we added a feature that isn't supported by bash v4 😅
