### ISSUE TITLE
status background is overriden when opening session using t

### ISSUE THREAD

**Issue by nicos68** [joshmedeski/t-smart-tmux-session-manager#68]
If I open tmux using the `tmux` command, the status background color corresponds to what I setup in my config :
![image](https://github.com/joshmedeski/t-smart-tmux-session-manager/assets/1062625/2b487c11-a875-419b-b296-d8637a7e0d65)
However, if I use `t myproject` to open a new session, my settings are ignored:
![image](https://github.com/joshmedeski/t-smart-tmux-session-manager/assets/1062625/bf7dabba-4a84-4e44-ba28-9241cbe7c967)
Also in this case, my nvim background color is wrong :
![image](https://github.com/joshmedeski/t-smart-tmux-session-manager/assets/1062625/7f04096a-5b3e-43fa-869d-c28a1dd93b0f)
whereas in the first case it is correct :
![image](https://github.com/joshmedeski/t-smart-tmux-session-manager/assets/1062625/2df455f9-8f95-43d8-aef4-d9d834e3aa67)

I set up a minimal reproducible example here :
https://codeberg.org/nise/dotfiles/src/branch/t-color-issue/.config/tmux/tmux.conf

**Comment by nicos68** [comment]
Ok so it looks like if I run `tmux new-session -As "tmux"` straight from my shell prompt it works as expected, but if I run it from a script file it reproduces the issue.

Would anyone have any advice ? Even though I concede that this looks more like an alacritty/tmux issue

**Comment by joshmedeski** [comment]
> The -A flag makes new-session behave like attach-session if session-name already exists

Can you confirm if your bug is reintroduced if you run `tmux new-session -s "tmux"`?

Perhaps it has something to do with the attach mechanism.

**Comment by nicos68** [comment]
> > The -A flag makes new-session behave like attach-session if session-name already exists
> 
> Can you confirm if your bug is reintroduced if you run `tmux new-session -s "tmux"`?
> 
> Perhaps it has something to do with the attach mechanism.

No, if I just remove the `-A` option the issue is not reproduced.

I just made a test with kitty and the colors look right, even when using `t`. So it looks like an alacritty issue :/ If you're curious you can have a look at my alacritty config [here](https://codeberg.org/nise/dotfiles/src/branch/t-color-issue/.config/alacritty/alacritty.yml)

**Comment by joshmedeski** [comment]
Alacritty recommends you set the TERM variable directly on your Alacritty config.

```yml
env:
  TERM: xterm-256color
```

https://github.com/joshmedeski/dotfiles/blob/dc421dd1b24dea5bb18fafcede68786ccbdc57ae/.config/alacritty/alacritty.yml#L14

**Comment by joshmedeski** [comment]
@nicos68 let me know if you're still seeing this issue.

**Comment by nicos68** [comment]
> Alacritty recommends you set the TERM variable directly on your Alacritty config.
> 
> ```yaml
> env:
>   TERM: xterm-256color
> ```
> 
> https://github.com/joshmedeski/dotfiles/blob/dc421dd1b24dea5bb18fafcede68786ccbdc57ae/.config/alacritty/alacritty.yml#L14

Thanks, that does fix the issue (after restarting alacritty, which may not be obvious).
