### ISSUE TITLE
t is too short - probably a better name is needed

### ISSUE THREAD

**Issue by GreenBlast** [joshmedeski/t-smart-tmux-session-manager#76]
Currently I'm using 't' as an alias to task warrior task command. 

I understand that probably it is very useful to use t as the command, but probably it would be preferred to give the bash script a more descriptive name like:

bin/smart-tmux-session-manager

and setting it to t could be done via an alias in the shell config file. (So you can set it to 't' or anything else actually

**Comment by GreenBlast** [comment]
And BTW kudos for the cool idea and execution, really neat.

**Comment by joshmedeski** [comment]
I don't want to make a breaking change for all the current users. But instead of adding it to your path you could create an alias that points to the `t` bin script directly if you'd like.

**Comment by GreenBlast** [comment]
Done that, I think that `a` is even more prestigious than `t` 😉
