### ISSUE TITLE
Add session previews from tmux-tea

### ISSUE THREAD

**Issue by 2KAbhishek** [joshmedeski/t-smart-tmux-session-manager#79]
Hey @joshmedeski, I recently released [tmux-tea](https://github.com/2kabhishek/tmux-tea) inspired by t, one of the extra features I added there was session previews.

I believe that can be added easily to t as well, if you're interested here's the link to the preview code:

https://github.com/2KAbhishek/tmux-tea/blob/19ccf2c575d73d6a5190016505233afa03c00185/bin/tea.sh#L19

lmk what you think or if you need any help adding this

**Comment by joshmedeski** [comment]
Cool, thanks for sharing! Always like seeing how people take my idea and make it their own.

**Comment by joshmedeski** [comment]
@omerxx just released a tmux session manager plugin that also has some nice preview features.

https://github.com/omerxx/tmux-sessionx/blob/main/scripts/preview.sh
