### ISSUE TITLE
Tmux Sessions not found

### ISSUE THREAD

**Issue by phortonssf** [joshmedeski/t-smart-tmux-session-manager#80]
When starting **t-smart** zoxide, fd work perfect!!! However, tmux sessions just hangs and finds no results. I have updated to the latest versions of all required packages and my fish shell. I did manage to get **sessions** however by setting sessions as the default search with the following. 

```
set -g @t-fzf-default-results 'sessions' 
```
Hope this helps someone else. 

**Update**
After using the tool some more the above code does work, but only if you don't navigate to any of the other searches, **zoxide, or fd**. If you return to **sessions** after viewing any of the other search options, no sessions are displayed like when T-smart** first loaded**.  For clarity **sessions** works on first load **only works** if set as default **and** no other searches are performed.

**Comment by joshmedeski** [comment]
I've noticed tmux sometimes hangs when you change a setting. I've found removing tmux's `tmp` code fixes the hang.

```sh
rm -rf /tmp/tmux-501
```

Hope this helps.

**Comment by phortonssf** [comment]
Thanks ran this instead there was no **tmux-501**
```
rm -rf /tmp/tmux-1000
```

Same problem though

**Comment by phortonssf** [comment]
Okay I got it.  Fish is my default shell in and out of tmux, but my bash shell was somehow pointing to a different tmux and not my brew install. So the first run would use the fish shell brew location but the secondary run on the bind:action in FZF was calling to bash and giving me the wrong version.  Fixed by removing tmux install in /bin/tmux and reinstalling tmux with homebrew.

**Comment by joshmedeski** [comment]
Got it, different versions of tmux would do it.
