### ISSUE TITLE
Make the previously active session selected by default

### ISSUE THREAD

**Issue by joebonneau** [joshmedeski/t-smart-tmux-session-manager#81]
Hey Josh,

Following up on our chat on Discord 😄 

As a user, I'd like to be able to mindlessly switch to the previously active session by bringing up the `t` prompt and hitting enter. In order to do this, it would probably make sense to remove the current session from the prompt. 

The reason I think this would be nice is that I've been finding it hard to keep track of all of my keybindings, and one that I've been finding particularly problematic is "switch to the previously active session" (cmd + l) vs. `t` (cmd + k). By condensing this into one keybinding, I can either quickly switch to the previous session or opt for doing something else, whether it's creating a new session or switching to another session.

I don't know that everyone would love this, so perhaps it could be an opt-in sort of feature.

Joe

**Comment by joshmedeski** [comment]
Thanks Joe,

I could add a "hide current sessions" optional feature flag. Should be pretty easy to implement.

**Comment by joebonneau** [comment]
Sounds great! Would that flag also make the previously active session selected by default?

**Comment by joshmedeski** [comment]
Yes, the sessions are already sorted by most recent use.
