### ISSUE TITLE
Crashes if no FZF_TMUX_OPTS set

### ISSUE THREAD

**Issue by lukeberry99** [joshmedeski/t-smart-tmux-session-manager#82]
If there are no `FZF_TMUX_OPTS` set then `t` crashes with the following output

```
[...]/bin/t: line 142: conditional binary operator expected
[...]/bin/t: line 142: syntax error near `$FZF_TMUX_OPTS'
[...]/bin/t: line 142: `                if [[ ! -v $FZF_TMUX_OPTS ]]; then'
```

Don't we want to be setting `-z` to check if `FZF_TMUX_OPTS` is unset, and if it is we give it a default value? Whereas right now we're checking if it is set, and then overwriting it if it is?

Happy to make a PR to this effect

**Comment by RayJameson** [comment]
+1 on this one, it seems like -v doesn't work correctly, check screenshot
<img width="1034" alt="image" src="https://github.com/joshmedeski/t-smart-tmux-session-manager/assets/67468725/217520e0-7964-4652-ba53-7768eb83de37">

**Comment by RayJameson** [comment]
After update it's working even with `-v`, I don't understand why, considering testing with `echo`, but at least I can set up my colorscheme

**Comment by joshmedeski** [comment]
It's stating a "syntax error". What version of bash is on your machine? (`bash --version`).

I require bash >= 4.0 for this project to properly work.

**Comment by lukeberry99** [comment]
I was running 3.2 - but I've upgraded to 5.2.21 and it does fix it.

For what it's worth, I do have a branch that gets this working for me in bash 3.x - https://github.com/lukeberry99/t-smart-tmux-session-manager/tree/fix/fzf-tmux-opts

But unsure if that's warranted, I missed the min bash version on the README and it works as expected if you're using the correct setup 😂

**Comment by joshmedeski** [comment]
I think it's a good idea to update the switch case. I will make a quick commit this week.
