### ISSUE TITLE
Tmux Pop-up Failing

### ISSUE THREAD

**Issue by b4rlw** [joshmedeski/t-smart-tmux-session-manager#88]
After updating, `t` is not launching the pop-up within Tmux - I updated the plugin itself at the same time as all my brew packages, so unsure which caused this issue (mistake). This issue manifests on both my SIP disabled M2 Mac Mini and my heavily locked down work M2 MBP, though both are running the same plugins and dotfiles.

I have `<prefix> T` bound to `cmd J` as per your suggestion in the initial video, but now I just see the cursor flicker in the middle of the screen without the pop-up actually launching. Occasionally, for a split second I will see:

`unknown option:  '` (Not sure what characters are actually in the space, I just see something similar to this)

This plugin is so good that I now feel lost without it! Any ideas what could be causing this?
I believe I'm running the latest version that only requires `bash v3`.

```
zoxide 0.9.2
fzf 0.44.1 (brew)
tmux 3.3a
```

**Comment by joshmedeski** [comment]
Yeah, all of this looks alright. Did you completely kill your tmux server and try again? Or even restart your computer?

**Comment by b4rlw** [comment]
The only other thing that I did was upgrade to Sonoma 14.1.2 - I take it things work as intended for you after the update?

**Comment by b4rlw** [comment]
Reinstalled macOS from scratch, setup all deps from scratch and it worked. However, after I pasted over my own `tmux.conf` it stopped working again and now is back to the non-launching state.

Even after removing `~/.config/tmux`, `tmp/tmux-501`, uninstalling Tmux with Brew, restarting the machine and beginning the Tmux installation from scratch again, it still isn't working!

Perhaps Tmux/TPM/t-smart-tmux-session-manager modifies something outside of these directories, that is preserving the brokenness 🤔

**Comment by joshmedeski** [comment]
Dude, I'm stumped. I used your `tmux.conf` exactly and I can't recreate your issue.

Can you join my Discord server: https://discord.gg/RQnZH7fFse

I can get on a call and help you one-on-one. (message me on the `#tmux` channel)

**Comment by b4rlw** [comment]
That's very generous of you. I've joined the server, but I won't ask for any more of your time until I've exhausted some more possibilities!

**Comment by b4rlw** [comment]
So, it was a tough one to reproduce, but I don't think it has anything to do with your plugin!
I believe this problem relates back to `fzf` -- and I wasn't being careful enough with my term variables.

Up until recently, it seems like all duplicates were permitted between `FZF_DEFAULT_OPTS` and `FZF_TMUX_OPTS`. However, I'm now finding that when:
```
--no-info
--pointer
--marker
--color
```
are included in `FZF_TMUX_OPTS`, it breaks your plugin.

If I simply copy `fzf-custom.fish` from your dotfiles, things work, as you don't have any of these duplicates present.
So it seems like panic over / case closed for now, though I'd be interested to know if you could reproduce this issue with the latest version of `fzf`!

Cheers.

**Comment by joshmedeski** [comment]
Great! I'm reworking how `fzf` variables are set so hopefully in the next few weeks there will be an update that prevents this kind of issue.
