### ISSUE TITLE
Command to switch to last session

### ISSUE THREAD

**Issue by jakkan** [joshmedeski/t-smart-tmux-session-manager#91]
I really like your plugin, thanks for maintaining it! This issue is a feature request/idea. I often switch between two thux sessions. Then my workflow looks kind of like this

work in a session
prefix+T, arrow up, enter
work in other session
prefix+T, arrow up, enter
work in first session

It would be great if there was another command to switch to the last session. Then my workflow would become

work in a session
prefix+Tab
work in other session
prefix+Tab
work in first session

**Comment by joshmedeski** [comment]
I use `<prefix>+L` to switch between two sessions constantly (almost more than I use my session manager).

Bonus tip: I've set it up to `cmd+l` in macOS on my terminal emulator to make it even easier to trigger.
